### PR TITLE
protocol: add support for optional command checksumming using '*'

### PR DESCRIPTION
**Pull request by zougloub**
While I haven't experienced data corruptions on grbl-based hardware, I have seen scary stuff elsewhere, and I value my fingers/house/machinery.

For extra-paranoid people, the checksumming feature as it's optional is not perfect, as it's still theoretically possible to have the '*' changing to... say... a '2', and the machine would just take a `G0 Z5 *24` as `G0Z5224` instead of `G0Z5`.

### CODE REVIEW

**Comment by chamnit** [comment]
Unfortunately, this would break every GUI.

**Comment by zougloub** [comment]
Hi @chamnit, how does it break every GUI?
Seems to me that the only possible breakage would be if a GUI sees the error in case of invalid checksum (error:17). And arguably breaking a GUI is better than breaking something else ;)
Is there anything else?
Apart from it, the GUI doesn't *have* to send the checksums, if that wasn't clear in the code.

Regards,

**Comment by chamnit** [comment]
@zougloub : Even if it's an option, there will be a certain percentage of users that will enable it and complain to GUI developers to support it. Right now, I'm not interested in altering anything related to the protocol until the next version comes out, which already includes has a checksum similar to yours. It'll be released to the public when it's ready beta-testing. That said, I do like your `*` format. I may use something similar to that.

In addition, Grbl on the 328p is completely maxed out. There is no more room to add anything except for critical bug fixes, because I literally have about a few hundred bytes of flash to work with for certain   builds I have to support.

**Comment by zougloub** [comment]
@chamnit I didn't invent the syntax `*` or the way to perform the checksum, it comes from http://reprap.org/wiki/G-code#.2A:_Checksum ; and the GUIs which support 3D printing may already support it :)

If it were me, I'd have used another mechanism, and any command/response would be identified (a la IMAP).

I started to take a look at the grbl code and maybe I'll contribute patches that save space or performance, who knows.

**Comment by electrokean** [comment]
And that appears to be derived from NMEA 0183 checksums, which only differs by using hexadecimal

**Comment by Harvie** [comment]
I have to agree that this would be super usefull. 

> Even if it's an option, there will be a certain percentage of users that will enable it and complain to GUI developers to support it.

Well. I am a GUI developer and i have exact opposite problem. People with sh*tty wiring and craptacular chinese usb-serial chips are complaining about mid-job failures and there is no useful way to prove it or deny it.

It might be a single byte lost in 3 hour long cycle. Very hard to debug.

Another problem that we face is when "ok" messages get lost/corrupted. The GUI just don't know that it can continue sending data (because few of tens of thousands commands were not properly acked) and we end up idling forewer...

**Comment by langwadt** [comment]
maybe something real simple, in the RX interrupt add every byte received to a 16 bit variable (or a fancier checksum) add an optional field to the status report with the 16 bit result.  A sender should be able to keep track of that

**Pull request closed without merging**
